import { NextPage } from "next";
import Head from "next/head";

import { SettingsView } from "@/views";

const SettingsPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Swipe and Matching now.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <SettingsView />
    </div>
  );
};

export default SettingsPage;
